return {
    blueprints       = false,   
    no_handcrafting  = false,  
    far_reach        = false,  
    show_signals     = true,  
    always_day       = false,  
    even_distribution = true,  
    auto_pipe_connectors = true, 
    fast_start       = false,  
    fast_start_mech  = false,  
    translate_chat     = true,   
    translate_overhead = true,  
    rate_calc        = true,   
    car_finder       = true,   
    feedback         = true,   
    circuit_highlight = true,  
    bp_params        = false,   
    debug_log        = false,  
}
