local Constants = {}
Constants.antigrief = {
    strikes_per_cycle = 5,
    kicks_before_ban = 1,
    strike_ttl_ticks = 18000,       
    kick_ttl_ticks = 216000,        
    tamper_warn_before_strike = 1,
    tamper_warn_ttl_ticks = 18000,   
    gui_open_whitelist = {
        ['wooden-chest'] = true,
        ['iron-chest'] = true,
        ['steel-chest'] = true,
    },
    blocked_vehicles = {
        ['tank'] = true,
    },
    long_text_warn_ttl_ticks = 108000,    
    decon_warn_ttl_min_ticks = 7200,      
    decon_warn_ttl_max_ticks = 18000,     
    capsule_bomb_threshold = 8,
    damage_entity_threshold = 20,
    damage_history_ttl_ticks = 18000,    
    robot_mining_cluster_time_threshold_ticks = 60,    
    robot_mining_cluster_distance_threshold = 50,
    robot_mining_cluster_max_count = 100,
    create_ghost_delay_ticks = 5,
    recreate_retry_ticks = 10,
    recreate_max_attempts = 18,
    recreate_teleport_radius = 8,
    history_limit_per_table = 2000,
    required_playtime_ticks = 648000,    
}
Constants.sessions = {
    trusted_value = 3 * 60 * 3600,                 
    required_only_time_to_save_time = 10 * 3600,   
    nth_tick = 5 * 3600,                           
}
Constants.jail = {
    group_name = 'jail',
    allowed_actions = { 'write_to_console','start_walking' },
    default_punish_mode = 'jail',
}
Constants.untrusted = {
    group_name = 'Untrusted',
    blocked_actions = {
        'import_blueprint_string',
        'open_blueprint_library_gui',
        'grab_blueprint_record',
        'drop_blueprint_record',
        'flush_opened_entity_fluid',
        'flush_opened_entity_specific_fluid',
        'flip_entity',
    },
}
Constants.spawn_logo = {
    sprite = 'file/img/world/logo-pad.png',
    scale = 0.32,
    render_layer = 'floor',
    position_offset = { x = 0, y = 0 },
    light = {
        enabled = true,
        sprite = 'utility/light_medium',
        scale = 6,
        minimum_darkness = 0.1,
    },
    text_lines = {},
}
Constants.audit = {
    mine = 'tried to mine %s (owner: %s)',
    mine_restore_failed = 'FAILED to restore %s at %s,%s surface %s (can_place=%s, owner: %s, blocked_by: %s)',
    deconstruct_mark = 'tried to mark %s for deconstruction (owner: %s)',
    deconstruct_ghost = 'tried to deconstruct ghost %s (owner: %s)',
    upgrade = 'tried to upgrade %s → %s (owner: %s)',
    rotate = 'tried to rotate %s (owner: %s)',
    damage = 'tried to damage %s (owner: %s)',               
    combat_destroy = 'tried to destroy %s with weapon/vehicle (owner: %s)', 
    gui_tamper = 'tried to open/modify %s GUI (owner: %s)',  
    paste_tamper = 'tried to paste settings onto %s (owner: %s)', 
    fast_transfer_tamper = 'tried to fast-transfer items to/from %s (owner: %s)', 
    flip = 'tried to flip %s (owner: %s)',                   
    mine_restore_ghost = 'placed GHOST of %s at %s,%s surface %s (owner: %s) — tile blocked, victim must rebuild',
    override_mine    = 'admin-override: mined %s (owner: %s)',
    override_decon   = 'admin-override: deconstructed %s (owner: %s)',
    override_ghost   = 'admin-override: deconstructed ghost %s (owner: %s)',
    override_upgrade = 'admin-override: upgraded %s (owner: %s)',
    override_rotate  = 'admin-override: rotated %s (owner: %s)',
    override_gui     = 'admin-override: opened/modified %s GUI (owner: %s)',
    override_paste   = 'admin-override: pasted settings onto %s (owner: %s)',
    override_combat  = 'admin-override: destroyed %s with weapon/vehicle (owner: %s)',
    override_fast_transfer = 'admin-override: fast-transferred items to/from %s (owner: %s)', 
    override_flip    = 'admin-override: flipped %s (owner: %s)', 
    banned_by = 'Banned by %s',                          
    hard_block_ban = 'Hard-block %s: %d strikes ignored after a kick (%s)',
    hard_block_kick = 'Kicked: interfering with %s belonging to other players. Reoffending after reconnect = permanent ban.',
    long_text_spam_ban = 'Long-text spam, 4× warnings ignored',
    mass_decon_ban = 'Mass decon, 4× warnings ignored',
    capsule_ban = 'Damaged: %s with: %s. This action was performed automatically.',
    jailed_by = 'Jailed by %s',
    nuke_equip = '%s tried to equip nukes but was not trusted.',
    capsule_equip = '%s equipped %s but was not trusted.',
    vehicle_blocked = '%s tried to drive a %s but was not trusted.', 
    capsule_damage = '%s damaged: %s with: %s',
    corpse_looting = '%s is looting %s´s body.',
    corpse_looted = '%s has looted %s´s body.',
    crafting = '%s canceled their craft of item %s of total count %s in raw items (%s slots) but had no inventory left.',
    mass_decon_alert = '[Deconstruct] %s tried to deconstruct: %s entities!',
    feedback_title = 'New report from %s',
}
Constants.todo_list = {
    window_max_height = 600,  
    max_title_len     = 200,  
    max_desc_len      = 1000, 
}
return Constants
