local Event = require 'lib.event'  
require 'lib.token'                
require 'lib.fancy_time'           
require 'lib.task'                 
require 'lib.chunk_jobs'           
require 'lib.config'               
require 'lib.debug_log'            
require 'lib.compat'               
require 'lib.server'               
require 'lib.sessions'             
require 'lib.jail'                 
require 'lib.untrusted'            
require 'lib.antigrief'            
require 'lib.commands'             
require 'commands.trust'           
require 'commands.fp'              
require 'commands.fpo'             
require 'lib.translate_chat_emit'  
require 'commands.sessions'        
require 'commands.news'            
require 'commands.jail'            
require 'gui.init'                 
require 'gui.top_buttons'          
require 'gui.antigrief_panel'      
require 'gui.admin_panel'          
require 'gui.welcome_screen'       
require 'lib.rate_calc'            
require 'gui.rate_calc_button'     
require 'gui.rate_calc_window'     
require 'lib.car_finder'           
require 'gui.car_finder_button'    
require 'lib.feedback'             
require 'gui.feedback_window'      
require 'gui.feedback_button'      
require 'lib.todo_list'            
require 'gui.todo_list_window'     
require 'gui.todo_list_dialog'     
require 'gui.todo_list_button'     
require 'gui.tools_panel'          
require 'lib.even_distribution'      
require 'gui.even_distribution_button' 
require 'lib.circuit_highlight'        
require 'gui.circuit_highlight_button' 
require 'lib.inserter_throughput'        
require 'gui.inserter_throughput_button' 
require 'lib.belt_visualizer'        
require 'gui.belt_visualizer_button' 
require 'lib.auto_pipe_connectors'        
require 'gui.auto_pipe_connectors_button' 
require 'lib.bp_params'            
require 'gui.bp_params_window'     
require 'gui.bp_params_button'     
require 'lib.spawn_logo'           
require 'lib.server_select'        
require 'gui.server_select_window' 
require 'gui.locales_menu'         
require 'gui.status_button'        
require 'gui.admin_panel.modules'  
_G.Server = require 'lib.server'   
_G.Token = require 'lib.token'     
_G.Sessions = require 'lib.sessions' 
_G.ServerSelect = require 'lib.server_select' 
Event.on_init(
    function()
        log('[factorio-polska] scenario loaded — all modules initialized')
        game.print({ 'fp-general.scenario-loaded' })
    end
)
